title: "Vinay Muralimohan - Cloud Architect Portfolio"
email: "vinaymrao@gmail.com"
description: "Portfolio showcasing my skills, certifications, projects and professional journey as a Cloud Architect."
baseurl: ""          # Leave empty for a user site
url: "https://vinzydev.github.io"
theme: jekyll-theme-slate
markdown: kramdown

kramdown:
  input: GFM

# Navigation pages (the Slate theme uses these for header links)
header_pages:
  - index.md
  - blog/index.md